apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  containers:
  - name: my-nginx
    image: nginx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-nginx-deploy
spec:
  template:
    metadata:
      labels:
        env: test 
    spec:
      containers:
      - name: my-nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
spec:
  selector:
    env: test
  ports:
    - protocol: TCP
      port: 80 
