apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: advanced-update-nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: '30%'
  minReadySeconds: 10
  replicas: 5
  selector:
    matchLabels:
      run: simple-nginx
  template:
    metadata:
      labels:
        run: simple-nginx
    spec:
      containers:
      - name: simple-nginx
        image: nginx
        ports:
        - containerPort: 80
