apiVersion: v1
kind: Service
metadata:
  name: pilot-nginx-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
  selector:
    project: pilot
    environment: production
    tier: frontend
