apiVersion: v1
kind: Pod
metadata:
  name: pilot.dev.nginx
  labels:
    project: pilot
    environment: develop
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pilot.dev.memcached
  labels:
    project: pilot
    environment: develop
    tier: cache
spec:
  containers:
    - name: memcached
      image: memcached
      ports:
      - containerPort: 11211
