apiVersion: v1
kind: Service
metadata:
  name: nginx-sts-svc-hl
  labels:
    app: nginx-sts
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: nginx-sts
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  serviceName: "nginx-sts-svc-hl"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      containers:
        - name: nginx-sts
          image: nginx
          ports:
          - containerPort: 80
      restartPolicy: Always
